### ISSUE TITLE
无法打包成exe可执行文件

### ISSUE THREAD

**Issue by thb007** [wongzeon/ICP-Checker#12]
执行命令```pyinstaller -i ICP备案.ico -F ICP-Checker.py```
![H QU1_N)ED`{UK{~WCCM V3](https://user-images.githubusercontent.com/17548936/178144513-44549aec-fca2-4d92-90d1-45dbdaf683ea.png)

**Comment by wongzeon** [comment]
这里面没有看到有什么有价值的报错信息，建议排查你的打包环境信息，打包前请确保依赖的库都悉数安装了。

**Comment by wongzeon** [comment]
看着是打包成功了，看看dist文件夹内是否有文件，截图的文件夹是build

**Comment by thb007** [comment]
> 看着是打包成功了，看看dist文件夹内是否有文件，截图的文件夹是build

没有生成exe文件

**Comment by thb007** [comment]
> 看着是打包成功了，看看dist文件夹内是否有文件，截图的文件夹是build

![M`_3AO{MDRJRWDO964T%MZR](https://user-images.githubusercontent.com/17548936/178144815-8079071d-e772-4612-9494-1a25e7b7ca18.png)

**Comment by wongzeon** [comment]
那只能你排查一下打包环境了，因为每个人的环境不一样，我使用pyinstaller打包是没问题的。

**Comment by wongzeon** [comment]
可以看看pyinstaller报错什么进行排查，谷歌一下

**Comment by thb007** [comment]
提示这个是不是查询太多ua被封了还是ip被拦截。
![4``9N~(59C SMP6}$HJ9})A](https://user-images.githubusercontent.com/17548936/178145062-df006104-7a86-4953-95ba-b29d4b9807b3.png)

**Comment by wongzeon** [comment]
嗯，对于过于频繁的请求的，会拉黑一段时间，如果前面的查询没问题，那就是这样，稍等重试吧

**Comment by thb007** [comment]
> 嗯，对于过于频繁的请求的，会拉黑一段时间，如果前面的查询没问题，那就是这样，稍等重试吧

那这样的话后期的支持列表查询封得更快了

**Comment by thb007** [comment]
如果采用python运行主程序提示这个

```
root@linux:~/ICP-Checker-2.1.4# python ICP-Checker.py
  File "ICP-Checker.py", line 124
    print(f"\n查询对象：{info} 共有 {domain_total} 个已备案域名\n")
                                                                              ^
SyntaxError: invalid syntax

```

**Comment by wongzeon** [comment]
所以一直没做，平时工作用不上这功能，正常也就查一两个网站，一两个公司这样。要批量查询，要么用第三方已经缓存了的数据，要么上代理和随机UA可能会好些。

**Comment by wongzeon** [comment]
> 如果采用python运行主程序提示这个
> 
> ```
> root@linux:~/ICP-Checker-2.1.4# python ICP-Checker.py
>   File "ICP-Checker.py", line 124
>     print(f"\n查询对象：{info} 共有 {domain_total} 个已备案域名\n")
>                                                                               ^
> SyntaxError: invalid syntax
> 
> ```

你试试查公司名会不会，我发布前测试了没问题呀😂

**Comment by thb007** [comment]
> 所以一直没做，平时工作用不上这功能，正常也就查一两个网站，一两个公司这样。要批量查询，要么用第三方已经缓存了的数据，要么上代理和随机UA可能会好些。

我想提取主流的域名用在科学上网上，呼呼呼，见笑了。

**Comment by thb007** [comment]
> > 如果采用python运行主程序提示这个
> > ```
> > root@linux:~/ICP-Checker-2.1.4# python ICP-Checker.py
> >   File "ICP-Checker.py", line 124
> >     print(f"\n查询对象：{info} 共有 {domain_total} 个已备案域名\n")
> >                                                                               ^
> > SyntaxError: invalid syntax
> > ```
> 
> 你试试查公司名会不会，我发布前测试了没问题呀😂

不行
```
root@linxu:~/ICP-Checker-2.1.4# python ICP-Checker.py 华为终端有限公司
  File "ICP-Checker.py", line 124
    print(f"\n查询对象：{info} 共有 {domain_total} 个已备案域名\n")
                                                                              ^
SyntaxError: invalid syntax

```

**Comment by wongzeon** [comment]
晚点我看看😂

**Comment by thb007** [comment]
> 晚点我看看😂
你懂的，你想搞个科学上网的白名单。哈哈哈。那我久关闭主题了。谢啦

**Comment by wongzeon** [comment]
> > > 如果采用python运行主程序提示这个
> > > ```
> > > root@linux:~/ICP-Checker-2.1.4# python ICP-Checker.py
> > >   File "ICP-Checker.py", line 124
> > >     print(f"\n查询对象：{info} 共有 {domain_total} 个已备案域名\n")
> > >                                                                               ^
> > > SyntaxError: invalid syntax
> > > ```
> > 
> > 
> > 你试试查公司名会不会，我发布前测试了没问题呀😂
> 
> 不行
> 
> ```
> root@linxu:~/ICP-Checker-2.1.4# python ICP-Checker.py 华为终端有限公司
>   File "ICP-Checker.py", line 124
>     print(f"\n查询对象：{info} 共有 {domain_total} 个已备案域名\n")
>                                                                               ^
> SyntaxError: invalid syntax
> ```

我这边下载最新源码测试了，在Windows 10/11，CentOS 7.5均未复现该问题。如果你有更改过源代码，检查一下，一般这个错误提示有可能是多了某个符号。

**Comment by thb007** [comment]
真不行

**Comment by thb007** [comment]
> 最新源码测试了，在Windows 10/11，CentOS 7.5均未复现该问题。如果你有更改过源

我用这个源码真的不行，也没有修改过。https://codeload.github.com/wongzeon/ICP-Checker/zip/refs/tags/2.1.4

**Comment by thb007** [comment]
@wongzeon [wongzeon](https://github.com/wongzeon)

![SDWEK%GAK@`UT81 LD8WAWQ](https://user-images.githubusercontent.com/17548936/178148649-ec53fa1e-f3bc-4d59-88dd-d45b008818e1.png)

**Comment by thb007** [comment]
不好意思使用python3可以。

**Comment by wongzeon** [comment]
> 不好意思使用python3可以。

😅嗯，Python版本要3.6及以上，ReadMe写了的

**Comment by thb007** [comment]
> > 不好意思使用python3可以。
> 
> 😅嗯，Python版本要3.6及以上，ReadMe写了的

嗯
