### ISSUE TITLE
好几个问题

### ISSUE THREAD

**Issue by hunteropA2** [wongzeon/ICP-Checker#13]
第一个：
所有单独.cn的域名一律提示不支持备案！但.org.cn  .com.cn  这一类的正常

第二个：
域名备案条件判断的问题，似乎有点多余吧,管网域名后缀我随便输入都可以提交上去显示空记录,也并没有提示不支持
是否可以去掉这个域名限制备案的判断？目前来看这个判断把单独的CN域名全拦截了

第三个：
是否可以添加多线程？批量查询？目前我尝试可以一次性复制几十条到窗口也是可以批量,但是量还是太小,有数量限制，而且遇到报错的也不知道是哪条域名报错没查询成功，能否在输入窗口支持输入txt格式的文件？读取txt里面的内容一条一条查询,然后把查询到的结果报错的域名单独导出xlsx，成功的在另一个xlsx,这样可以明确知道哪些没成功,方便后续重查

第四个：
报错问题,以下是遇到过的错误：
获取Sign遇到错误，请重试！
The previously referenced variable "t_response"
计算图片缺口位置错误，请重试！
有时候重试几次就可以查出来有时候必须重启服务器才可以正常查询

方便留个TG的话最好  我每天查询域名备案量很大  可以帮助你完善程序

**Comment by wongzeon** [comment]
## 第一个：

已定位原因，正则内缺少单独的cn，是拉去管局可备案域名时遗漏了，之前只测试了中文域名如：“网址之家.cn”是可以查询的，是我疏漏了。**已发版修复，感谢指出！**

最新Release：[2.1.5](https://github.com/wongzeon/ICP-Checker/releases/tag/2.1.5)

## 第二个：

加入域名可否备案判断，是我的个人需求。原因是既然该域名类型不可备案，则避免不必要的请求，当然你去管局查询，是可以通过查询的，会返回空白列表。

***域名类型判断在`query_base`函数之中，可以进行修改、替换或移除。***

## 第三个：

感谢建议，将增加报错记录。

批量查询暂不考虑。我做这个的目的是为了方便我的工作，日常工作偶尔需要查询一两个域名或公司，不想每次都拉那个缺口验证，经常会拉失败。有空做UI界面后，再完善这个功能。

多线程以后也不考虑。一个是，短时间内大量的查询，会导致IP被封禁；另一个是这样的行为可能会对查询系统带来一些影响。

源码已提供，如有这样的需求，可自行修改加入，欢迎提交PR

## 第四个：

这个一般都是查询次数过多之后出现的，有时候管局的服务器也会抽风，报内部错误（500）。无论是哪一种导致的，都得等几分钟后再重试。

如果是请求多次后出现的，那么实际上出现Sign错误的时候，后面的错误就是必然的，因为此时IP被拉黑了，请求都会返回成功，但是内容是错误的，建议是等待几分钟后再进行重试。

## Thanks

再次感谢你的建议和反馈，之后有意见与建议，仍然是发issue就好了
