### ISSUE TITLE
遇到过几次查询错误的情况

### ISSUE THREAD

**Issue by DWIF1** [wongzeon/ICP-Checker#14]
连续查多条的时候   会有一些明明有备案但是返回结果是查询无备案,遇到过好几次了,不知道哪里的问题  判断还是缓存  过一会查询就能继续查到实际结果了    希望排查下

**Comment by wongzeon** [comment]
这个是因为查询过多、过快导致的，管局在返回查询结果时拉黑了IP，返回正常空数据，导致无法判断出是没备案还是被屏蔽，在其他步骤被拉黑的话，程序会提示出错的。

具体已在 #13 里解答了。

**Comment by DWIF1** [comment]
能测出查询频率吗

**Comment by DWIF1** [comment]
有备案的空结果和无备案的空结果应该返回数据有区别的吧    聚查那边查询失败就可以分的很清

**Comment by wongzeon** [comment]
获取token失败（被拉黑，或者服务器内部错误时）可以判断。

频率你可以自行测试一下，我目前看是不固定的。我以公司名查，最多的时候连续查个5、6次，没问题，你可以试试，连续查阿里，百度，腾讯，这几个备案多的公司。

本项目和第三方先把数据爬下来做缓存的模式不一样。

**Comment by DWIF1** [comment]
明白   能否写一个IP池的多线程查询功能    这样可以避免频率问题

**Comment by wongzeon** [comment]
多线程不考虑，在#13已解答，代理可以在requests里加proxy参数进行切换，欢迎PR
