### ISSUE TITLE
备案查询功能是否可以集成到我的项目domain-admin

### ISSUE THREAD

**Issue by mouday** [wongzeon/ICP-Checker#19]
基于Python3 + Vue3.js 技术栈实现的域名和SSL证书监测平台
https://github.com/mouday/domain-admin

![image](https://github.com/1in9e/icp-domains/assets/24365682/c2cd570a-12e5-47d5-a58f-717f3672191c)

**Comment by wongzeon** [comment]
可以的，不过我这个是基于opencv去做那个拖动验证的，可能效率会低一些，如果不是对于实时性、官方一致性要求很高的话，也可以用第三方的API查询备案

**Comment by mouday** [comment]
感谢，我采用了第三方的方式接入，感谢提供思路
