### ISSUE TITLE
好像那个网站封了 查不到数据

### ISSUE THREAD

**Issue by LycEcho** [wongzeon/ICP-Checker#2]

**Comment by wongzeon** [comment]
那个网站是工信部的，不会封的。

查询程序也没有被封，如果提示错误码403，那么稍等使用或者自行更换头部UA、Cookies等就好了。

最新测试可用 2021年7月9日

![query.png](http://ww1.sinaimg.cn/large/001NakGngy1gsalbq8ju0j617n0gctau02.jpg)
