### ISSUE TITLE
或许你需要这个浏览器插件 【ICP Query Extension】 - 一款方便查询网站 ICP 备案、Whois、DNS、服务器位置及运营商的浏览器插件

### ISSUE THREAD

**Issue by yuedanlabs** [wongzeon/ICP-Checker#20]
## 工具名称

ICP Query Extension

## 适用浏览器

暂时只有 Chrome 浏览器

## 简介

Browser Extension for ICP Query
一款开源的浏览器插件，方便以下功能：

- ICP 备案查询
- Whois 查询
- DNS 查询
- 服务器位置及运营商

## 下载地址

- chrome 应用商店商店
https://chrome.google.com/webstore/detail/icp-query-extension/plmfnmaihcmijdanpbondfejclejejfa
- zip 打包文件
https://github.com/yuedanlabs/icp-query-extension/releases

## 开源地址

https://github.com/yuedanlabs/icp-query-extension

## 示例图片

![image](https://github.com/ruanyf/weekly/assets/95392548/7f8efe20-0d9c-4d3f-81f4-0a8c4bd4d872)

**最后，喜欢的话，不求 star，也不求评价，请尽情享用你的快乐时光吧😋**
**但如果你愿意放下繁忙的工作只为支持一下我们的开源，我们也非常感谢🙏   ([点我去 star](https://github.com/yuedanlabs/icp-query-extension))**

**Comment by wongzeon** [comment]
这个和我的需求不是很匹配，只能显示当前浏览的域名信息，但通常来说只要是备案的域名，在页面底部会悬挂备案号，不过是个不错的项目，加油
