### ISSUE TITLE
11

### ISSUE THREAD

**Issue by know35** [wongzeon/ICP-Checker#26]
大佬们，这个是不是不能用了，查询什么都是无备案
![image](https://github.com/wongzeon/ICP-Checker/assets/64142915/aeb82b90-35c6-4915-a2a3-ccc314af8bfe)

**Comment by wongzeon** [comment]
刚测试了，可用的，请使用最新代码，如果是之前的exe打包版本，确实是失效了，因为查询的API在9月份的时候新增了参数。

已打包新版本 [2.1.8](https://github.com/wongzeon/ICP-Checker/releases/tag/2.1.8)，可下载使用，也可以自行使用源码打包。
