### ISSUE TITLE
部分企业查询异常

### ISSUE THREAD

**Issue by ysdxj** [wongzeon/ICP-Checker#27]
存在特殊符号的企业，特殊符号会被删除掉，导致查询错误

**Comment by ysdxj** [comment]
你好，比如，一汽—大众汽车有限公司，《语文报》社有限责任公司这样的企业名称。
![image](https://github.com/wongzeon/ICP-Checker/assets/86157883/87904721-5513-417b-b211-9b9a43c8b8f2)
![image](https://github.com/wongzeon/ICP-Checker/assets/86157883/73da2da0-ac77-4340-bd5f-608d99db180d)

**Comment by wongzeon** [comment]
收到🫡，感谢反馈

**Comment by wongzeon** [comment]
已修复 [ICP-Checker_V2.1.9](https://ghproxy.com/https://github.com/wongzeon/ICP-Checker/releases/download/2.1.9/ICP-Checker_V2.1.9.exe)
