### ISSUE TITLE
计算图片缺口位置错误，请重试！

### ISSUE THREAD

**Issue by dxd3819** [wongzeon/ICP-Checker#29]
貌似有点bug了，大佬能更新下吗

![image](https://github.com/wongzeon/ICP-Checker/assets/10613892/b18ef2c2-87c9-4be0-ad69-647c6760e3ca)

**Comment by wongzeon** [comment]
工信部的验证码形式变更了，不是计算缺口了，所以产生的错误，正在看能不能弄
