### ISSUE TITLE
大佬图形验证码方式换了，有空再写一个吗

### ISSUE THREAD

**Issue by Dyrookie** [wongzeon/ICP-Checker#32]

**Comment by wongzeon** [comment]
嗯，变成点字的了，得看看怎么弄

**Comment by loobug** [comment]
https://github.com/MgArcher/Text_select_captcha 
大佬 这个可以借鉴吗

**Comment by wongzeon** [comment]
看了一下，有点不太一样，如果是selenium的倒是就可以用这个轮子

**Comment by f4s1on** [comment]
> 感谢提供参考，这个可以获取到文字坐标，现在要看加密是怎么处理的

加密方式是AES/ECB/pkcs7的模式

**Comment by likohank** [comment]
> > 感谢提供参考，这个可以获取到文字坐标，现在要看加密是怎么处理的
> 
> 加密方式是AES/ECB/pkcs7的模式，密钥是参数secretKey，大佬有没有方法可以将文字和他的坐标对应起来，大部分库好像只会返回坐标 ![image](https://user-images.githubusercontent.com/57355558/282679911-6973c69b-e5a3-4715-92d0-fd79cc4a4929.png)
> 
> ![image](https://user-images.githubusercontent.com/57355558/282679777-d1b54dcd-ff36-482e-bc97-863ab4cb29f2.png)

简单的话， 应该把候选词 4个字的图片， 做个 ocr 识别， 筛选出4个字， 然后逐次做4次识别， 就能拿到顺序对应的4个坐标。

**Comment by wongzeon** [comment]
> > 感谢提供参考，这个可以获取到文字坐标，现在要看加密是怎么处理的
> 
> 加密方式是AES/ECB/pkcs7的模式，密钥是参数secretKey，大佬有没有方法可以将文字和他的坐标对应起来，大部分库好像只会返回坐标 ![image](https://user-images.githubusercontent.com/57355558/282679911-6973c69b-e5a3-4715-92d0-fd79cc4a4929.png)
> 
> ![image](https://user-images.githubusercontent.com/57355558/282679777-d1b54dcd-ff36-482e-bc97-863ab4cb29f2.png)

应该先取候选词顺序，再获取大图的坐标，然后再加密回传，应该就OK了

**Comment by f4s1on** [comment]
因为它会同时返回一个大图和一个候选词图片，候选词图片的文字很工整，所以很容易识别，但是想从大图中识别每个文字就精度很低了，我用的是ddddocr库

**Comment by xiaoming9261** [comment]
希望大佬早日完成，身体健康

**Comment by wongzeon** [comment]
> 因为它会同时返回一个大图和一个候选词图片，候选词图片的文字很工整，所以很容易识别，但是想从大图中识别每个文字就精度很低了，我用的是ddddocr库

是的，ddddocr的api版本用“通用|早期(汉字)点选-Cls”这个模型倒是识别准确率还可以，基本都能识别，但就是没有给出模型，手头只有一台辣鸡笔记本，训练太慢了😂还得再看看别的

**Comment by wongzeon** [comment]
> 希望大佬早日完成，身体健康

感谢支持~

**Comment by Dowww007** [comment]
> > 希望大佬早日完成，身体健康
> 
> 感谢支持~



> > 因为它会同时返回一个大图和一个候选词图片，候选词图片的文字很工整，所以很容易识别，但是想从大图中识别每个文字就精度很低了，我用的是ddddocr库
> 
> 是的，ddddocr的api版本用“通用|早期(汉字)点选-Cls”这个模型倒是识别准确率还可以，基本都能识别，但就是没有给出模型，手头只有一台辣鸡笔记本，训练太慢了😂还得再看看别的

需要机器吗？我可以免费提供

**Comment by f4s1on** [comment]
这里有一个比较类似的验证码的训练方式https://aistudio.baidu.com/projectdetail/6329495?channelType=0&channel=0，可以先收集一些数据集用它这种方式训练看看

**Comment by ImYrS** [comment]
@wongzeon 我来, 这两天 push 上来, 不用研究了

**Comment by wongzeon** [comment]
> > > 希望大佬早日完成，身体健康
> > 
> > 
> > 感谢支持~
> 
> > > 因为它会同时返回一个大图和一个候选词图片，候选词图片的文字很工整，所以很容易识别，但是想从大图中识别每个文字就精度很低了，我用的是ddddocr库
> > 
> > 
> > 是的，ddddocr的api版本用“通用|早期(汉字)点选-Cls”这个模型倒是识别准确率还可以，基本都能识别，但就是没有给出模型，手头只有一台辣鸡笔记本，训练太慢了😂还得再看看别的
> 
> 需要高配机器的话，我可以免费提供，就当为公益项目做贡献了

目前已经解决了 [ICP-Checker_V2.2.0.exe](https://ghproxy.com/https://github.com/wongzeon/ICP-Checker/releases/download/2.2.0/ICP-Checker_V2.2.0.exe)，感谢热心的朋友！
