### ISSUE TITLE
计算图片缺口位置错误，请重试！

### ISSUE THREAD

**Issue by liang-hiwin** [wongzeon/ICP-Checker#34]
获取Token，请等待……

已获取到Token，查询中，速度取决于网站响应，请等待……
计算图片缺口位置错误，请重试！

**Comment by liang-hiwin** [comment]
获取Token，请等待……

已获取到Token，查询中，速度取决于网站响应，请等待……
计算图片缺口位置错误，请重试！

**Comment by wongzeon** [comment]
#32 工信部验证方式发生了变更，等新版吧
