### ISSUE TITLE
大佬，向您询问一些学习问题

### ISSUE THREAD

**Issue by ystvapp** [wongzeon/ICP-Checker#38]
您好，大佬

想请问 这一段

```
self.base_url = 'https://hlwicpfwc.miit.gov.cn/icpproject_query/api/'
self.auth_url = self.base_url + 'auth' # 返回token
self.image_url = self.base_url + 'image/getCheckImagePoint' # 返回Secretkey、uuid
self.check_url = self.base_url + 'image/checkImage' # 返回Sign，传值里的token是uuid
self.query_url = self.base_url + 'icpAbbreviateInfo/queryByCondition' # 标头需要：cookie、token、sign、uuid
```
Token, Secretkey, Uuid 都成功获取到了。

在 check_url 那边，是如何成功请求到的？它里面需要

```
{
    "token": "xxx",
    "secretKey": "xxx",
    "clientUid": "xxx",
    "pointJson": "xxx"
}
```

这个 pointJson是如何生成出来的呀？我这儿学习把逻辑移去PHP端上 卡在这边了 麻烦了 谢谢您。

**Comment by wongzeon** [comment]
Check_url 这部分，pointJson是对验证码点选得到坐标，进行AES加密得到的。使用AES-ECB模式，key则是image_url返回的secretKey。

未加密前的数据为JSON格式，结构如下：

```json
[
  {
    "x": 123,
    "y": 123
  },
  {
    "x": 123,
    "y": 123
  },
  {
    "x": 123,
    "y": 123
  },
  {
    "x": 123,
    "y": 123
  }
]
```

**Comment by ystvapp** [comment]
这段程序在python代码内是没的吗？是否能指点下代码部分是在哪儿 我好参考 谢谢您！

**Comment by ystvapp** [comment]
> Check_url 这部分，pointJson是对验证码点选得到坐标，进行AES加密得到的。使用AES-ECB模式，key则是image_url返回的secretKey。
> 
> 未加密前的数据为JSON格式，结构如下：
> 
> ```json
> [
>   {
>     "x": 123,
>     "y": 123
>   },
>   {
>     "x": 123,
>     "y": 123
>   },
>   {
>     "x": 123,
>     "y": 123
>   },
>   {
>     "x": 123,
>     "y": 123
>   }
> ]
> ```


这段程序在python代码内是没的吗？是否能指点下代码部分是在哪儿 我好参考 谢谢您！

**Comment by wongzeon** [comment]
嗯是的，因为已经不需要了，就删除了。有兴趣的可以看看 https://file.io/QujYCbdb19uL

**Comment by ystvapp** [comment]
> 嗯是的，因为已经不需要了，就删除了。有兴趣的可以看看 https://file.io/QujYCbdb19uL

您说已经不需要了 那现在最新版本的代码内 是怎么做到请求成功的呀？

**Comment by wongzeon** [comment]
你走一遍代码应该就明白了，甚至可能自己测试一下也会顿悟😂，祝好

**Comment by ystvapp** [comment]
> 你走一遍代码应该就明白了，甚至可能自己测试一下也会顿悟😂，祝好

希望大佬可以指点指点 主要现在就是卡在 pointJson 这个，不知道如何获取到这个值 进行 checkImage 的请求
