### ISSUE TITLE
可否付费定制一些功能？

### ISSUE THREAD

**Issue by Dowww007** [wongzeon/ICP-Checker#39]
我需求是定时检查某一些域名备案是否还在，如果域名备案被注销，则通过**软件通知我。

**Comment by wongzeon** [comment]
我弄这个不盈利的，无需付费。你这个只需要简单改改，自己应该也能搞定的。把要查询的对象固定成列表，跳过输入过滤的步骤，直接查询，然后判断结果，再推送通知。跑个定时任务，通知的可以用bark，或者企业微信。
