### ISSUE TITLE
Do you know of a similar project for Node?

### ISSUE THREAD

**Issue by pcristov** [wongzeon/ICP-Checker#7]
Hello, do you know of a similar project for Node? Thank you in advance.

**Comment by wongzeon** [comment]
I'm sorry I don't know if there are other similar project for Node. 

But there a project may fit your needs, [icp-extensions](https://github.com/qingyeyun/icp-extensions) is a browser extension for check domain's ICP license information.

 By the way, it check the ICP license information from third-party API not from the official ways.
