### ISSUE TITLE
[Errno 2] No such file or directory: '%USERPROFILE%/Desktop/备案信息.xlsx'

### ISSUE THREAD

**Issue by thb007** [wongzeon/ICP-Checker#9]
电脑桌面直接运行，窗口里面提示这个
![4DQ5B电脑桌面直接运行，窗口里面提示这个
_ 3~ZG~JJ%$E6E{H](https://user-images.githubusercontent.com/17548936/178010551-eb3e56e0-cf40-49e1-baa6-7123690affbb.png)

**Comment by wongzeon** [comment]
系统什么版本？

**Comment by thb007** [comment]
> 系统什么版本？

win10专业版 21H2

**Comment by wongzeon** [comment]
已修复，可以正常使用了。因为我的环境是改了默认桌面路径的，默认路径考虑到。

PS. 推荐还是更改一下桌面路径比较好，以免重装的时候丢失文件。
